services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: client
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
